### ISSUE TITLE
Missing file 

### ISSUE THREAD

**Issue by Lutacon** [rgomezcasas/dotfiles#11]
The file login_init.zsh is missing from the repo.

Used in `shell/zsh/.zlogin`

**Comment by rgomezcasas** [comment]
It does exist! `ls "$ZIM_HOME/login_init.zsh"`
![image](https://user-images.githubusercontent.com/1331435/88228795-f9a50880-cc6f-11ea-81d6-9d90ca21dddc.png)
But first you need to setup [Zim](https://github.com/zimfw/zimfw) (that it's done when applying all the submodules)

😬
