### ISSUE TITLE
Not able to find the installer files

### ISSUE THREAD

**Issue by rohinrohin** [rgomezcasas/dotfiles#14]
Hey, 

Excellent repo and collection of dotfiles. However I am not able to install it with the commands in the readme. I see that the installer files doesn't exist in the repo.

`bash <(curl -s https://raw.githubusercontent.com/rgomezcasas/dotfiles/master/installer)
`

Let me know what I should run to install it. 

Thanks!

**Comment by rgomezcasas** [comment]
Try to install https://github.com/CodelyTV/dotly directly better 😊

**Comment by rohinrohin** [comment]
Hi, I want to mimic the exact same setup (with Raycast, etc.. ) which is not available in the dotly repo. Could you tell me how I can install your exact config? Thanks!
