### ISSUE TITLE
Listado de comandos disponibles en "dot" es muy lento, ejecuta un sh por cada item disponible.

### ISSUE THREAD

**Issue by splanes** [rgomezcasas/dotfiles#9]
Hola Rafa

En relación a "dot". Noté que tarda en printar los comandos disponibles. Señalo la línea que se lleva el tiempo de ejecución.
https://github.com/rgomezcasas/dotfiles/blob/b23b2337ed0659b5152b49e59d8af2387db9ef50/bin/dot#L25

Que te parece reemplazar
`xargs -I % sh -c 'echo "$(basename $(dirname %)) $(basename %)"' |`
por
`awk -F"/" '{print $(NF-1) " " $NF}' |`

de esa manera te evitas abrir un nuevo sh para ejecutar el echo y la ejecución pasa a ser instantánea.

Siento tener poco tiempo para subir un PR. Será para la próxima!

Fantástico codebase, me haz hecho tremendamente feliz 🥇 🥇 🥇 🥇

**Comment by rgomezcasas** [comment]
Pues me parece perfecto 😬  https://github.com/rgomezcasas/dotfiles/commit/3a612517edec2a9c886df21cf03fe9dee91c767a

Muchas gracias!! 😊

**Comment by splanes** [comment]
Gracias a tí! Un placer ayudarte
